/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppConferenciaRouteImport } from './routes/app.conferencia'
import { Route as AppBaseRouteImport } from './routes/app.base'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConferenciaRoute = AppConferenciaRouteImport.update({
  id: '/conferencia',
  path: '/conferencia',
  getParentRoute: () => AppRoute,
} as any)
const AppBaseRoute = AppBaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/base': typeof AppBaseRoute
  '/app/conferencia': typeof AppConferenciaRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/base': typeof AppBaseRoute
  '/app/conferencia': typeof AppConferenciaRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/base': typeof AppBaseRoute
  '/app/conferencia': typeof AppConferenciaRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/base'
    | '/app/conferencia'
    | '/app/dashboard'
    | '/app/relatorios'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/base'
    | '/app/conferencia'
    | '/app/dashboard'
    | '/app/relatorios'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/base'
    | '/app/conferencia'
    | '/app/dashboard'
    | '/app/relatorios'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conferencia': {
      id: '/app/conferencia'
      path: '/conferencia'
      fullPath: '/app/conferencia'
      preLoaderRoute: typeof AppConferenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/base': {
      id: '/app/base'
      path: '/base'
      fullPath: '/app/base'
      preLoaderRoute: typeof AppBaseRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBaseRoute: typeof AppBaseRoute
  AppConferenciaRoute: typeof AppConferenciaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBaseRoute: AppBaseRoute,
  AppConferenciaRoute: AppConferenciaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
